using System;
using student_council.Views;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.Reflection;

namespace student_council.Views
{
    /// <summary>
    /// Логика взаимодействия для DirectoriesWindow.xaml
    /// </summary>
    public partial class DirectoriesWindow : Window
    {
        
        public DirectoriesWindow()
        {
            InitializeComponent();
            DGridDirections.ItemsSource = student_council_kitEntities.GetContext().directions.ToList();
        }

        private void btn_event_direct_Click(object sender, RoutedEventArgs e)
        {
            Hide();
            new Events_DirectionsWindow((sender as Button).DataContext as directions).ShowDialog();
        }

        private void btn_exit_Click(object sender, RoutedEventArgs e)
        {
            Personal_AccountWindow personal_AccountWindow = new Personal_AccountWindow(AutorizationWindow.user);
            Hide();
            personal_AccountWindow.Show();
        }

        private void DGridDirections_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (DataGridColumn column in DGridDirections.Columns)
            {
                if (column is DataGridTextColumn)
                {
                    DataGridTextColumn textColumn = column as DataGridTextColumn;
                    Style style = DGridDirections.Resources["wordWrapStyle"] as Style;
                }
            }
        }
    }
}
