using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace student_council.Views
{
    /// <summary>
    /// Логика взаимодействия для Сomposition_of_Student_CouncilWindow.xaml
    /// </summary>
    public partial class Сomposition_of_Student_CouncilWindow : Window
    {
        public Сomposition_of_Student_CouncilWindow()
        {
            InitializeComponent();
            DGridCouncil.ItemsSource = student_council_kitEntities.GetContext().posts_stud_View.Where(x => x.id_post != null).ToList();
        }

        private void btn_exit_Click(object sender, RoutedEventArgs e)
        {
            Personal_AccountWindow personal_AccountWindow = new Personal_AccountWindow(AutorizationWindow.user);
            Hide();
            personal_AccountWindow.Show();
        }

        private void DGridDirections_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (DataGridColumn column in DGridCouncil.Columns)
            {
                if (column is DataGridTextColumn)
                {
                    DataGridTextColumn textColumn = column as DataGridTextColumn;
                    Style style = DGridCouncil.Resources["wordWrapStyle"] as Style;
                }
            }
        }

        private void btn_back_Click(object sender, RoutedEventArgs e)
        {
            Personal_AccountWindow personal_AccountWindow = new Personal_AccountWindow(AutorizationWindow.user);
            Hide();
            personal_AccountWindow.Show();
        }
    }
}
