//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_council
{
    using System;
    using System.Collections.Generic;
    
    public partial class creater_rehearsal_View
    {
        public int id_rehearsal { get; set; }
        public System.DateTime date { get; set; }
        public int id_creater { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string name_post { get; set; }
        public int id_user { get; set; }
        public string name_user { get; set; }
        public string surname_user { get; set; }
        public string patronymic_user { get; set; }
    }
}
