//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_council
{
    using System;
    using System.Collections.Generic;
    
    public partial class enter_history
    {
        public int id { get; set; }
        public string login { get; set; }
        public System.DateTime enter_date { get; set; }
        public int id_status { get; set; }
    
        public virtual status_enter status_enter { get; set; }
    }
}
