//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_council
{
    using System;
    using System.Collections.Generic;
    
    public partial class events_participant
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_event { get; set; }
    
        public virtual events events { get; set; }
        public virtual users users { get; set; }
    }
}
