//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_council
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_change_View
    {
        public int id_event { get; set; }
        public string name { get; set; }
        public string name_event { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public int id_destiny { get; set; }
        public int num_place { get; set; }
        public string name_status { get; set; }
    }
}
