//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_council
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_council_kitEntities : DbContext
    {
        private static student_council_kitEntities _context = new student_council_kitEntities();
        public student_council_kitEntities()
            : base("name=student_council_kitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static student_council_kitEntities GetContext()
        {
            if( _context == null )
                _context = new student_council_kitEntities();
            return _context;
        }
    
        public virtual DbSet<direction_participant> direction_participant { get; set; }
        public virtual DbSet<directions> directions { get; set; }
        public virtual DbSet<distiny> distiny { get; set; }
        public virtual DbSet<enter_history> enter_history { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<events_participant> events_participant { get; set; }
        public virtual DbSet<faculties> faculties { get; set; }
        public virtual DbSet<posts> posts { get; set; }
        public virtual DbSet<rehearsals> rehearsals { get; set; }
        public virtual DbSet<rehearsals_participant> rehearsals_participant { get; set; }
        public virtual DbSet<status_enter> status_enter { get; set; }
        public virtual DbSet<status_event> status_event { get; set; }
        public virtual DbSet<student_council> student_council { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<creater_rehearsal_View> creater_rehearsal_View { get; set; }
        public virtual DbSet<direction_stud_View> direction_stud_View { get; set; }
        public virtual DbSet<enter_stud_View> enter_stud_View { get; set; }
        public virtual DbSet<event_change_View> event_change_View { get; set; }
        public virtual DbSet<events_stud_View> events_stud_View { get; set; }
        public virtual DbSet<posts_stud_View> posts_stud_View { get; set; }
    }
}
